import { AnswerValue, Answers, ReportData, SharedQuestionnaire } from "@/types/questionnaire";
import { supabase } from "@/lib/supabase/client";
type DbQuestionnaire = { id:string; mode:string; relationship_date:string; creator_name:string; partner_name:string|null; creator_completed:boolean; partner_completed:boolean; created_at:string; updated_at:string; invite_token?:string };
const toQuestionnaire=(row:DbQuestionnaire):SharedQuestionnaire=>({id:row.id,mode:row.mode as SharedQuestionnaire["mode"],relationshipDate:row.relationship_date,creatorName:row.creator_name,partnerName:row.partner_name,creatorCompleted:row.creator_completed,partnerCompleted:row.partner_completed,createdAt:row.created_at,updatedAt:row.updated_at,inviteToken:row.invite_token});
const rpc=async<T>(name:string,args:Record<string,unknown>)=>{const {data,error}=await supabase.rpc(name,args);if(error)throw new Error(error.message);return data as T};
export async function createSharedQuestionnaire(creatorName:string,relationshipDate:string,answers:Record<string,AnswerValue>){const rows=await rpc<{questionnaire_id:string;creator_token:string;invite_token:string}[]>("create_questionnaire",{p_mode:"couple",p_creator_name:creatorName,p_relationship_date:relationshipDate,p_answers:answers});const created=rows[0];if(!created?.questionnaire_id||!created.creator_token||!created.invite_token)throw new Error("问卷创建成功，但未收到有效邀请信息。请重新提交。");return created;}
export async function getInvite(id:string,token:string){const rows=await rpc<DbQuestionnaire[]>("get_questionnaire_invite",{p_questionnaire_id:id,p_invite_token:token});return rows[0]?toQuestionnaire(rows[0]):null;}
export async function submitPartner(id:string,token:string,name:string,answers:Record<string,AnswerValue>){await rpc("submit_partner_answers",{p_questionnaire_id:id,p_invite_token:token,p_partner_name:name,p_answers:answers});}
export async function getCreatorStatus(id:string,token:string){const rows=await rpc<DbQuestionnaire[]>("get_creator_status",{p_questionnaire_id:id,p_creator_token:token});return rows[0]?toQuestionnaire(rows[0]):null;}
export async function getReport(id:string,token:string){const data=await rpc<{questionnaire:DbQuestionnaire;creator_answers:Record<string,AnswerValue>;partner_answers:Record<string,AnswerValue>}>("get_questionnaire_report",{p_questionnaire_id:id,p_access_token:token});return {questionnaire:toQuestionnaire(data.questionnaire),answers:{creator:data.creator_answers,partner:data.partner_answers}} as ReportData;}
